<hr> <p><b>SoC Product Marketing Manager -  Silicon Valley</b></p>
             Contact Maureen Smerdon <a href=mailto:Maureen.smerdon@xilinx.com>Maureen.smerdon@xilinx.com</a><br>
             Posted 2015-07-30<br>
             Info: <a href='/opportunities/20150730-1.pdf' target='_blank'>/opportunities/20150730-1.pdf</a>
             <br><br>
             <hr> <p><b>Embedded Electronics Engineer -  Livermore, CA</b></p>
             Contact Bill Spain <a href=mailto:arlin@gdca.com>arlin@gdca.com</a><br>
             Posted 2016-05-09<br>
             Info: <a href='' target='_blank'></a>
             <br><br>
             